#Server Port
server : 
  port : 8888

spring :
  #Oracle Setting
  datasource : 
    driver-class-name : oracle.jdbc.driver.OracleDriver
    url : jdbc:oracle:thin:@localhost:1521/xe
    username : jpanda
    password : jpanda
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: najungbeen@gmail.com
    password: skwjdqls12@
    properties:
      mail:
        smtp:
          auth: true
          starttls: # 추가 안하면 SMTPSendFailedException
            enalble: true
            required: true  
  #HttpHiddenMethod
  mvc: 
    hiddenmethod:
      filter:
        enabled: true

#myBatis
mybatis: 
  config-location: classpath:configuration/njb.xml
  mapper-locations: classpath:mappers/**/*.xml
 

