#Server Port
server : 
  port : 8888

spring :
  #Oracle Setting
  datasource : 
    driver-class-name : oracle.jdbc.driver.OracleDriver
    url : jdbc:oracle:thin:@localhost:1521/xe
    username : jpanda
    password : jpanda
  #HttpHiddenMethod
  mvc: 
    hiddenmethod:
      filter:
        enabled: true

#myBatis
mybatis: 
  config-location: classpath:configuration/bsm.xml
  mapper-locations: classpath:mappers/bsm/*.xml


