#Server Port
server : 
  port : 8080

spring :
  #Oracle Setting
  datasource : 
    driver-class-name : oracle.jdbc.driver.OracleDriver
    url : jdbc:oracle:thin:@database-1.canmygoaixjp.ap-northeast-2.rds.amazonaws.com/JPANDA
    username : admin
    password : adminadmin


  mail:
    host: smtp.gmail.com 
    port: 587
    username: jpandajb501@gmail.com
    password: ldxpeltvbuvsonge
    properties:
      mail:
        smtp:
          auth: true 
          starttls:
            enable: true

  #HttpHiddenMethod
  mvc: 
    hiddenmethod:
      filter:
        enabled: true

  #resolver
  thymeleaf:
    prefix: classpath:/templates/

#myBatis
mybatis: 
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/**/*.xml

